/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.btpn.opera.operationsurvey.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Responden service. Represents a row in the &quot;responden&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.btpn.opera.operationsurvey.model.impl.RespondenModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.btpn.opera.operationsurvey.model.impl.RespondenImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Responden
 * @generated
 */
@ProviderType
public interface RespondenModel extends BaseModel<Responden> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a responden model instance should use the {@link Responden} interface instead.
	 */

	/**
	 * Returns the primary key of this responden.
	 *
	 * @return the primary key of this responden
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this responden.
	 *
	 * @param primaryKey the primary key of this responden
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this responden.
	 *
	 * @return the ID of this responden
	 */
	public long getId();

	/**
	 * Sets the ID of this responden.
	 *
	 * @param id the ID of this responden
	 */
	public void setId(long id);

	/**
	 * Returns the nik of this responden.
	 *
	 * @return the nik of this responden
	 */
	@AutoEscape
	public String getNik();

	/**
	 * Sets the nik of this responden.
	 *
	 * @param nik the nik of this responden
	 */
	public void setNik(String nik);

	/**
	 * Returns the full name of this responden.
	 *
	 * @return the full name of this responden
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this responden.
	 *
	 * @param fullName the full name of this responden
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the lob of this responden.
	 *
	 * @return the lob of this responden
	 */
	@AutoEscape
	public String getLob();

	/**
	 * Sets the lob of this responden.
	 *
	 * @param lob the lob of this responden
	 */
	public void setLob(String lob);

	/**
	 * Returns the division of this responden.
	 *
	 * @return the division of this responden
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this responden.
	 *
	 * @param division the division of this responden
	 */
	public void setDivision(String division);

	/**
	 * Returns the surveyoperation ID of this responden.
	 *
	 * @return the surveyoperation ID of this responden
	 */
	public long getSurveyoperationId();

	/**
	 * Sets the surveyoperation ID of this responden.
	 *
	 * @param surveyoperationId the surveyoperation ID of this responden
	 */
	public void setSurveyoperationId(long surveyoperationId);

	/**
	 * Returns the total value of this responden.
	 *
	 * @return the total value of this responden
	 */
	public double getTotalValue();

	/**
	 * Sets the total value of this responden.
	 *
	 * @param totalValue the total value of this responden
	 */
	public void setTotalValue(double totalValue);

	/**
	 * Returns the answer record of this responden.
	 *
	 * @return the answer record of this responden
	 */
	@AutoEscape
	public String getAnswerRecord();

	/**
	 * Sets the answer record of this responden.
	 *
	 * @param answerRecord the answer record of this responden
	 */
	public void setAnswerRecord(String answerRecord);

	/**
	 * Returns the submitted date of this responden.
	 *
	 * @return the submitted date of this responden
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this responden.
	 *
	 * @param submittedDate the submitted date of this responden
	 */
	public void setSubmittedDate(Date submittedDate);

	/**
	 * Returns the notes of this responden.
	 *
	 * @return the notes of this responden
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this responden.
	 *
	 * @param notes the notes of this responden
	 */
	public void setNotes(String notes);

}