/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package responden.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SurveyResponden service. Represents a row in the &quot;survey_responden&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>responden.model.impl.SurveyRespondenModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>responden.model.impl.SurveyRespondenImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SurveyResponden
 * @generated
 */
@ProviderType
public interface SurveyRespondenModel extends BaseModel<SurveyResponden> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey responden model instance should use the {@link SurveyResponden} interface instead.
	 */

	/**
	 * Returns the primary key of this survey responden.
	 *
	 * @return the primary key of this survey responden
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey responden.
	 *
	 * @param primaryKey the primary key of this survey responden
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this survey responden.
	 *
	 * @return the ID of this survey responden
	 */
	public long getId();

	/**
	 * Sets the ID of this survey responden.
	 *
	 * @param id the ID of this survey responden
	 */
	public void setId(long id);

	/**
	 * Returns the nik of this survey responden.
	 *
	 * @return the nik of this survey responden
	 */
	@AutoEscape
	public String getNik();

	/**
	 * Sets the nik of this survey responden.
	 *
	 * @param nik the nik of this survey responden
	 */
	public void setNik(String nik);

	/**
	 * Returns the survey ID of this survey responden.
	 *
	 * @return the survey ID of this survey responden
	 */
	public long getSurveyId();

	/**
	 * Sets the survey ID of this survey responden.
	 *
	 * @param surveyId the survey ID of this survey responden
	 */
	public void setSurveyId(long surveyId);

	/**
	 * Returns the answer1 of this survey responden.
	 *
	 * @return the answer1 of this survey responden
	 */
	public Double getAnswer1();

	/**
	 * Sets the answer1 of this survey responden.
	 *
	 * @param answer1 the answer1 of this survey responden
	 */
	public void setAnswer1(Double answer1);

	/**
	 * Returns the answer2 of this survey responden.
	 *
	 * @return the answer2 of this survey responden
	 */
	public Double getAnswer2();

	/**
	 * Sets the answer2 of this survey responden.
	 *
	 * @param answer2 the answer2 of this survey responden
	 */
	public void setAnswer2(Double answer2);

	/**
	 * Returns the answer3 of this survey responden.
	 *
	 * @return the answer3 of this survey responden
	 */
	public Double getAnswer3();

	/**
	 * Sets the answer3 of this survey responden.
	 *
	 * @param answer3 the answer3 of this survey responden
	 */
	public void setAnswer3(Double answer3);

	/**
	 * Returns the answer4 of this survey responden.
	 *
	 * @return the answer4 of this survey responden
	 */
	public Double getAnswer4();

	/**
	 * Sets the answer4 of this survey responden.
	 *
	 * @param answer4 the answer4 of this survey responden
	 */
	public void setAnswer4(Double answer4);

	/**
	 * Returns the answer5 of this survey responden.
	 *
	 * @return the answer5 of this survey responden
	 */
	public Double getAnswer5();

	/**
	 * Sets the answer5 of this survey responden.
	 *
	 * @param answer5 the answer5 of this survey responden
	 */
	public void setAnswer5(Double answer5);

	/**
	 * Returns the answer6 of this survey responden.
	 *
	 * @return the answer6 of this survey responden
	 */
	public Double getAnswer6();

	/**
	 * Sets the answer6 of this survey responden.
	 *
	 * @param answer6 the answer6 of this survey responden
	 */
	public void setAnswer6(Double answer6);

	/**
	 * Returns the answer7 of this survey responden.
	 *
	 * @return the answer7 of this survey responden
	 */
	public Double getAnswer7();

	/**
	 * Sets the answer7 of this survey responden.
	 *
	 * @param answer7 the answer7 of this survey responden
	 */
	public void setAnswer7(Double answer7);

	/**
	 * Returns the answer8 of this survey responden.
	 *
	 * @return the answer8 of this survey responden
	 */
	public Double getAnswer8();

	/**
	 * Sets the answer8 of this survey responden.
	 *
	 * @param answer8 the answer8 of this survey responden
	 */
	public void setAnswer8(Double answer8);

	/**
	 * Returns the answer9 of this survey responden.
	 *
	 * @return the answer9 of this survey responden
	 */
	public Double getAnswer9();

	/**
	 * Sets the answer9 of this survey responden.
	 *
	 * @param answer9 the answer9 of this survey responden
	 */
	public void setAnswer9(Double answer9);

	/**
	 * Returns the answer10 of this survey responden.
	 *
	 * @return the answer10 of this survey responden
	 */
	public Double getAnswer10();

	/**
	 * Sets the answer10 of this survey responden.
	 *
	 * @param answer10 the answer10 of this survey responden
	 */
	public void setAnswer10(Double answer10);

	/**
	 * Returns the note of this survey responden.
	 *
	 * @return the note of this survey responden
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this survey responden.
	 *
	 * @param note the note of this survey responden
	 */
	public void setNote(String note);

	/**
	 * Returns the status of this survey responden.
	 *
	 * @return the status of this survey responden
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this survey responden.
	 *
	 * @param status the status of this survey responden
	 */
	public void setStatus(String status);

	/**
	 * Returns the submitted date of this survey responden.
	 *
	 * @return the submitted date of this survey responden
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this survey responden.
	 *
	 * @param submittedDate the submitted date of this survey responden
	 */
	public void setSubmittedDate(Date submittedDate);

}