/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.btpn.opera.operationsurvey.model.impl;

import com.btpn.opera.operationsurvey.model.Answers;
import com.btpn.opera.operationsurvey.model.AnswersModel;
import com.btpn.opera.operationsurvey.model.AnswersSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Answers service. Represents a row in the &quot;answers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>AnswersModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnswersImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnswersImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AnswersModelImpl
	extends BaseModelImpl<Answers> implements AnswersModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a answers model instance should use the <code>Answers</code> interface instead.
	 */
	public static final String TABLE_NAME = "answers";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"answer", Types.VARCHAR},
		{"value", Types.DOUBLE}, {"questions_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("answer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("questions_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table answers (id LONG not null primary key,answer VARCHAR(100) null,value DOUBLE,questions_id LONG)";

	public static final String TABLE_SQL_DROP = "drop table answers";

	public static final String ORDER_BY_JPQL = " ORDER BY answers.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY answers.id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long QUESTIONSID_COLUMN_BITMASK = 1L;

	public static final long ID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Answers toModel(AnswersSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Answers model = new AnswersImpl();

		model.setId(soapModel.getId());
		model.setAnswer(soapModel.getAnswer());
		model.setValue(soapModel.getValue());
		model.setQuestionsId(soapModel.getQuestionsId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Answers> toModels(AnswersSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Answers> models = new ArrayList<Answers>(soapModels.length);

		for (AnswersSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AnswersModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Answers.class;
	}

	@Override
	public String getModelClassName() {
		return Answers.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Answers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Answers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Answers, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Answers)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Answers, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Answers, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Answers)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Answers, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Answers, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Answers>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Answers.class.getClassLoader(), Answers.class, ModelWrapper.class);

		try {
			Constructor<Answers> constructor =
				(Constructor<Answers>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Answers, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Answers, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Answers, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Answers, Object>>();
		Map<String, BiConsumer<Answers, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Answers, ?>>();

		attributeGetterFunctions.put("id", Answers::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Answers, Long>)Answers::setId);
		attributeGetterFunctions.put("answer", Answers::getAnswer);
		attributeSetterBiConsumers.put(
			"answer", (BiConsumer<Answers, String>)Answers::setAnswer);
		attributeGetterFunctions.put("value", Answers::getValue);
		attributeSetterBiConsumers.put(
			"value", (BiConsumer<Answers, Double>)Answers::setValue);
		attributeGetterFunctions.put("questionsId", Answers::getQuestionsId);
		attributeSetterBiConsumers.put(
			"questionsId", (BiConsumer<Answers, Long>)Answers::setQuestionsId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getAnswer() {
		if (_answer == null) {
			return "";
		}
		else {
			return _answer;
		}
	}

	@Override
	public void setAnswer(String answer) {
		_answer = answer;
	}

	@JSON
	@Override
	public double getValue() {
		return _value;
	}

	@Override
	public void setValue(double value) {
		_value = value;
	}

	@JSON
	@Override
	public long getQuestionsId() {
		return _questionsId;
	}

	@Override
	public void setQuestionsId(long questionsId) {
		_columnBitmask |= QUESTIONSID_COLUMN_BITMASK;

		if (!_setOriginalQuestionsId) {
			_setOriginalQuestionsId = true;

			_originalQuestionsId = _questionsId;
		}

		_questionsId = questionsId;
	}

	public long getOriginalQuestionsId() {
		return _originalQuestionsId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Answers.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Answers toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Answers>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnswersImpl answersImpl = new AnswersImpl();

		answersImpl.setId(getId());
		answersImpl.setAnswer(getAnswer());
		answersImpl.setValue(getValue());
		answersImpl.setQuestionsId(getQuestionsId());

		answersImpl.resetOriginalValues();

		return answersImpl;
	}

	@Override
	public int compareTo(Answers answers) {
		long primaryKey = answers.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Answers)) {
			return false;
		}

		Answers answers = (Answers)obj;

		long primaryKey = answers.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		AnswersModelImpl answersModelImpl = this;

		answersModelImpl._originalQuestionsId = answersModelImpl._questionsId;

		answersModelImpl._setOriginalQuestionsId = false;

		answersModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Answers> toCacheModel() {
		AnswersCacheModel answersCacheModel = new AnswersCacheModel();

		answersCacheModel.id = getId();

		answersCacheModel.answer = getAnswer();

		String answer = answersCacheModel.answer;

		if ((answer != null) && (answer.length() == 0)) {
			answersCacheModel.answer = null;
		}

		answersCacheModel.value = getValue();

		answersCacheModel.questionsId = getQuestionsId();

		return answersCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Answers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Answers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Answers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Answers)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Answers, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Answers, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Answers, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Answers)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Answers>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id;
	private String _answer;
	private double _value;
	private long _questionsId;
	private long _originalQuestionsId;
	private boolean _setOriginalQuestionsId;
	private long _columnBitmask;
	private Answers _escapedModel;

}