/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package operation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Questions service. Represents a row in the &quot;questions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>operation.model.impl.QuestionsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>operation.model.impl.QuestionsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Questions
 * @generated
 */
@ProviderType
public interface QuestionsModel extends BaseModel<Questions> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a questions model instance should use the {@link Questions} interface instead.
	 */

	/**
	 * Returns the primary key of this questions.
	 *
	 * @return the primary key of this questions
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this questions.
	 *
	 * @param primaryKey the primary key of this questions
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this questions.
	 *
	 * @return the ID of this questions
	 */
	public long getId();

	/**
	 * Sets the ID of this questions.
	 *
	 * @param id the ID of this questions
	 */
	public void setId(long id);

	/**
	 * Returns the question of this questions.
	 *
	 * @return the question of this questions
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this questions.
	 *
	 * @param question the question of this questions
	 */
	public void setQuestion(String question);

}