/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package operation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SurveyObject service. Represents a row in the &quot;survey_object&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>operation.model.impl.SurveyObjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>operation.model.impl.SurveyObjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SurveyObject
 * @generated
 */
@ProviderType
public interface SurveyObjectModel extends BaseModel<SurveyObject> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey object model instance should use the {@link SurveyObject} interface instead.
	 */

	/**
	 * Returns the primary key of this survey object.
	 *
	 * @return the primary key of this survey object
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey object.
	 *
	 * @param primaryKey the primary key of this survey object
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this survey object.
	 *
	 * @return the ID of this survey object
	 */
	public long getId();

	/**
	 * Sets the ID of this survey object.
	 *
	 * @param id the ID of this survey object
	 */
	public void setId(long id);

	/**
	 * Returns the name of this survey object.
	 *
	 * @return the name of this survey object
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this survey object.
	 *
	 * @param name the name of this survey object
	 */
	public void setName(String name);

}