/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package operation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SurveyOperation service. Represents a row in the &quot;survey_operation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>operation.model.impl.SurveyOperationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>operation.model.impl.SurveyOperationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SurveyOperation
 * @generated
 */
@ProviderType
public interface SurveyOperationModel extends BaseModel<SurveyOperation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a survey operation model instance should use the {@link SurveyOperation} interface instead.
	 */

	/**
	 * Returns the primary key of this survey operation.
	 *
	 * @return the primary key of this survey operation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this survey operation.
	 *
	 * @param primaryKey the primary key of this survey operation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this survey operation.
	 *
	 * @return the ID of this survey operation
	 */
	public long getId();

	/**
	 * Sets the ID of this survey operation.
	 *
	 * @param id the ID of this survey operation
	 */
	public void setId(long id);

	/**
	 * Returns the title of this survey operation.
	 *
	 * @return the title of this survey operation
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this survey operation.
	 *
	 * @param title the title of this survey operation
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this survey operation.
	 *
	 * @return the description of this survey operation
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this survey operation.
	 *
	 * @param description the description of this survey operation
	 */
	public void setDescription(String description);

	/**
	 * Returns the survey obj of this survey operation.
	 *
	 * @return the survey obj of this survey operation
	 */
	@AutoEscape
	public String getSurveyObj();

	/**
	 * Sets the survey obj of this survey operation.
	 *
	 * @param surveyObj the survey obj of this survey operation
	 */
	public void setSurveyObj(String surveyObj);

	/**
	 * Returns the start date of this survey operation.
	 *
	 * @return the start date of this survey operation
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this survey operation.
	 *
	 * @param startDate the start date of this survey operation
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this survey operation.
	 *
	 * @return the end date of this survey operation
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this survey operation.
	 *
	 * @param endDate the end date of this survey operation
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the submitted date of this survey operation.
	 *
	 * @return the submitted date of this survey operation
	 */
	public Date getSubmittedDate();

	/**
	 * Sets the submitted date of this survey operation.
	 *
	 * @param submittedDate the submitted date of this survey operation
	 */
	public void setSubmittedDate(Date submittedDate);

}