/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.btpn.opera.operationsurvey.service.base;

import com.btpn.opera.operationsurvey.model.SurveyOperationUsersView;
import com.btpn.opera.operationsurvey.service.SurveyOperationUsersViewLocalService;
import com.btpn.opera.operationsurvey.service.persistence.AnswersPersistence;
import com.btpn.opera.operationsurvey.service.persistence.QuestionsFinder;
import com.btpn.opera.operationsurvey.service.persistence.QuestionsPersistence;
import com.btpn.opera.operationsurvey.service.persistence.RespondenPersistence;
import com.btpn.opera.operationsurvey.service.persistence.SurveyObjectPersistence;
import com.btpn.opera.operationsurvey.service.persistence.SurveyOperationFinder;
import com.btpn.opera.operationsurvey.service.persistence.SurveyOperationPersistence;
import com.btpn.opera.operationsurvey.service.persistence.SurveyOperationUsersViewPersistence;
import com.btpn.opera.operationsurvey.service.persistence.SurveyOperationViewPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.annotation.versioning.ProviderType;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the survey operation users view local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.btpn.opera.operationsurvey.service.impl.SurveyOperationUsersViewLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.btpn.opera.operationsurvey.service.impl.SurveyOperationUsersViewLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class SurveyOperationUsersViewLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements SurveyOperationUsersViewLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SurveyOperationUsersViewLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.btpn.opera.operationsurvey.service.SurveyOperationUsersViewLocalServiceUtil</code>.
	 */

	/**
	 * Adds the survey operation users view to the database. Also notifies the appropriate model listeners.
	 *
	 * @param surveyOperationUsersView the survey operation users view
	 * @return the survey operation users view that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SurveyOperationUsersView addSurveyOperationUsersView(
		SurveyOperationUsersView surveyOperationUsersView) {

		surveyOperationUsersView.setNew(true);

		return surveyOperationUsersViewPersistence.update(
			surveyOperationUsersView);
	}

	/**
	 * Creates a new survey operation users view with the primary key. Does not add the survey operation users view to the database.
	 *
	 * @param id the primary key for the new survey operation users view
	 * @return the new survey operation users view
	 */
	@Override
	@Transactional(enabled = false)
	public SurveyOperationUsersView createSurveyOperationUsersView(long id) {
		return surveyOperationUsersViewPersistence.create(id);
	}

	/**
	 * Deletes the survey operation users view with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the survey operation users view
	 * @return the survey operation users view that was removed
	 * @throws PortalException if a survey operation users view with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SurveyOperationUsersView deleteSurveyOperationUsersView(long id)
		throws PortalException {

		return surveyOperationUsersViewPersistence.remove(id);
	}

	/**
	 * Deletes the survey operation users view from the database. Also notifies the appropriate model listeners.
	 *
	 * @param surveyOperationUsersView the survey operation users view
	 * @return the survey operation users view that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SurveyOperationUsersView deleteSurveyOperationUsersView(
		SurveyOperationUsersView surveyOperationUsersView) {

		return surveyOperationUsersViewPersistence.remove(
			surveyOperationUsersView);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SurveyOperationUsersView.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return surveyOperationUsersViewPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.btpn.opera.operationsurvey.model.impl.SurveyOperationUsersViewModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return surveyOperationUsersViewPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.btpn.opera.operationsurvey.model.impl.SurveyOperationUsersViewModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return surveyOperationUsersViewPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return surveyOperationUsersViewPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return surveyOperationUsersViewPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SurveyOperationUsersView fetchSurveyOperationUsersView(long id) {
		return surveyOperationUsersViewPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the survey operation users view with the primary key.
	 *
	 * @param id the primary key of the survey operation users view
	 * @return the survey operation users view
	 * @throws PortalException if a survey operation users view with the primary key could not be found
	 */
	@Override
	public SurveyOperationUsersView getSurveyOperationUsersView(long id)
		throws PortalException {

		return surveyOperationUsersViewPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			surveyOperationUsersViewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SurveyOperationUsersView.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			surveyOperationUsersViewLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			SurveyOperationUsersView.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			surveyOperationUsersViewLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SurveyOperationUsersView.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return surveyOperationUsersViewLocalService.
			deleteSurveyOperationUsersView(
				(SurveyOperationUsersView)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return surveyOperationUsersViewPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the survey operation users views.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.btpn.opera.operationsurvey.model.impl.SurveyOperationUsersViewModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of survey operation users views
	 * @param end the upper bound of the range of survey operation users views (not inclusive)
	 * @return the range of survey operation users views
	 */
	@Override
	public List<SurveyOperationUsersView> getSurveyOperationUsersViews(
		int start, int end) {

		return surveyOperationUsersViewPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of survey operation users views.
	 *
	 * @return the number of survey operation users views
	 */
	@Override
	public int getSurveyOperationUsersViewsCount() {
		return surveyOperationUsersViewPersistence.countAll();
	}

	/**
	 * Updates the survey operation users view in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param surveyOperationUsersView the survey operation users view
	 * @return the survey operation users view that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SurveyOperationUsersView updateSurveyOperationUsersView(
		SurveyOperationUsersView surveyOperationUsersView) {

		return surveyOperationUsersViewPersistence.update(
			surveyOperationUsersView);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SurveyOperationUsersViewLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		surveyOperationUsersViewLocalService =
			(SurveyOperationUsersViewLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SurveyOperationUsersViewLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SurveyOperationUsersView.class;
	}

	protected String getModelClassName() {
		return SurveyOperationUsersView.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				surveyOperationUsersViewPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected AnswersPersistence answersPersistence;

	@Reference
	protected QuestionsPersistence questionsPersistence;

	@Reference
	protected QuestionsFinder questionsFinder;

	@Reference
	protected RespondenPersistence respondenPersistence;

	@Reference
	protected SurveyObjectPersistence surveyObjectPersistence;

	@Reference
	protected SurveyOperationPersistence surveyOperationPersistence;

	@Reference
	protected SurveyOperationFinder surveyOperationFinder;

	protected SurveyOperationUsersViewLocalService
		surveyOperationUsersViewLocalService;

	@Reference
	protected SurveyOperationUsersViewPersistence
		surveyOperationUsersViewPersistence;

	@Reference
	protected SurveyOperationViewPersistence surveyOperationViewPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}